version: "3.9"

networks:
  lot-network:

volumes:
  pgdata:
  redisdata:

services:
  postgres:
    image: postgres:16
    container_name: lot-postgres
    environment:
      POSTGRES_USER: lot_user
      POSTGRES_PASSWORD: lot_pass
      POSTGRES_DB: lot_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lot-network

  redis:
    image: redis:7
    container_name: lot-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - lot-network